### PR TITLE
Retuned Shooter for new tape + four bar intaking 

### PR DESCRIPTION
**Pull request by Vernonicuhhh**
We need to test some more convenience features before merging in. Also launchpad shot is very sketch since field ceiling is too low.

### CODE REVIEW

**Comment by Vernonicuhhh** [comment]
If merged in we can close #74 as changes will be redundant

**Comment by Vernonicuhhh** [comment]
This branch also has the 6-ball auto but we have to tune the one sussy point at the end of practice day. Also retune launch pad shot. @awesomeyooner

**Comment by Vernonicuhhh** [comment]
This should also close #83 and #82

**Review by awesomeyooner — APPROVED** [review]
⭐️👍

**Pull request merged**
